server:
  port: 8080
spring:
  application:
    name: springbootTest
  profiles:
    include: application-log4j2.yml
    #@value获取属性值，只能通过application-开头的配置文件获取，并且得是active的文件
    active: log4j2,db
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/sakila?serverTimezone=Asia/Shanghai
    password: 123456
    username: root


#logging:
#  config: classpath:application-log4j2.yml

mybatis:
  #自定义拦截器sql显示属性
  showSql: true
  #自定义拦截器分页属性
  enablePage: true
  mapper-locations: classpath:mapping/*.xml
  configuration:
    # 使全局的映射器启用或禁用缓存
    cache-enabled: true
    # 全局启用或禁用延迟加载。当禁用时，所有关联对象都会即时加载
    lazy-loading-enabled: true
    # 当启用时，有延迟加载属性的对象在被调用时将会完全加载任意属性。否则，每种属性将会按需要加载。
    aggressive-lazy-loading: false
    # 是否允许单条sql 返回多个数据集 (取决于驱动的兼容性)default:true
    multiple-result-sets-enabled: true
    # 是否可以使用列的别名 (取决于驱动的兼容性) default:true
    use-column-label: true
    # 允许JDBC 生成主键。需要驱动器支持。如果设为了true，这个设置将强制使用被生成的主键，
    # 有一些驱动器不兼容不过仍然可以执行。 default:false
    use-generated-keys: true
    # 指定 MyBatis 如何自动映射 数据基表的列 NONE：不隐射\u3000PARTIAL:部分 FULL:全部
    auto-mapping-behavior: partial
    #     这是默认的执行类型 （SIMPLE: 简单；
    #     REUSE:执行器可能重复使用prepared statements语句；
    #     BATCH: 执行器可以重复执行语句和批量更新）
    default-executor-type: REUSE
    #  使用驼峰命名法转换字段。
    map-underscore-to-camel-case: true
    #设置本地缓存范围 session:就会有数据的共享
    #statement:语句范围 (这样就不会有数据的共享 )
    #defalut:session
    local-cache-scope: session
    # 设置但JDBC类型为空时,某些驱动程序 要指定值,default:OTHER，插入空值时不需要指定类型
    jdbc-type-for-null: null
    #  如果数据为空的字段，则该字段省略不显示，可以通过添加配置文件，规定查询数据为空是则返回null。
    call-setters-on-nulls: true




