package com.lq.springdemo.entity;

import com.lq.springdemo.entity.common.Page;

import java.util.Date;

public class Actor extends Page {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column actor.actor_id
     *
     * @mbg.generated Tue Aug 30 10:37:43 CST 2022
     */
    private Short actorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column actor.first_name
     *
     * @mbg.generated Tue Aug 30 10:37:43 CST 2022
     */
    private String firstName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column actor.last_name
     *
     * @mbg.generated Tue Aug 30 10:37:43 CST 2022
     */
    private String lastName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column actor.last_update
     *
     * @mbg.generated Tue Aug 30 10:37:43 CST 2022
     */
    private Date lastUpdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actor.actor_id
     *
     * @return the value of actor.actor_id
     *
     * @mbg.generated Tue Aug 30 10:37:43 CST 2022
     */
    public Short getActorId() {
        return actorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actor.actor_id
     *
     * @param actorId the value for actor.actor_id
     *
     * @mbg.generated Tue Aug 30 10:37:43 CST 2022
     */
    public void setActorId(Short actorId) {
        this.actorId = actorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actor.first_name
     *
     * @return the value of actor.first_name
     *
     * @mbg.generated Tue Aug 30 10:37:43 CST 2022
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actor.first_name
     *
     * @param firstName the value for actor.first_name
     *
     * @mbg.generated Tue Aug 30 10:37:43 CST 2022
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actor.last_name
     *
     * @return the value of actor.last_name
     *
     * @mbg.generated Tue Aug 30 10:37:43 CST 2022
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actor.last_name
     *
     * @param lastName the value for actor.last_name
     *
     * @mbg.generated Tue Aug 30 10:37:43 CST 2022
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column actor.last_update
     *
     * @return the value of actor.last_update
     *
     * @mbg.generated Tue Aug 30 10:37:43 CST 2022
     */
    public Date getLastUpdate() {
        return lastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column actor.last_update
     *
     * @param lastUpdate the value for actor.last_update
     *
     * @mbg.generated Tue Aug 30 10:37:43 CST 2022
     */
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actor
     *
     * @mbg.generated Tue Aug 30 10:37:43 CST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", actorId=").append(actorId);
        sb.append(", firstName=").append(firstName);
        sb.append(", lastName=").append(lastName);
        sb.append(", lastUpdate=").append(lastUpdate);
        sb.append("]");
        return sb.toString();
    }
}